# Generated by Django 6.0 on 2025-12-08 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, help_text='US State name', max_length=100)),
                ('year', models.IntegerField(db_index=True, help_text='Year of the crime report', validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2025)])),
                ('population', models.IntegerField(help_text='State population for the given year', validators=[django.core.validators.MinValueValidator(0)])),
                ('property_rate_all', models.FloatField(help_text='Total property crime rate per 100,000 population', validators=[django.core.validators.MinValueValidator(0)])),
                ('property_rate_burglary', models.FloatField(help_text='Burglary rate per 100,000 population', validators=[django.core.validators.MinValueValidator(0)])),
                ('property_rate_larceny', models.FloatField(help_text='Larceny rate per 100,000 population', validators=[django.core.validators.MinValueValidator(0)])),
                ('property_rate_motor', models.FloatField(help_text='Motor vehicle theft rate per 100,000 population', validators=[django.core.validators.MinValueValidator(0)])),
                ('violent_rate_all', models.FloatField(help_text='Total violent crime rate per 100,000 population', validators=[django.core.validators.MinValueValidator(0)])),
                ('violent_rate_assault', models.FloatField(help_text='Assault rate per 100,000 population', validators=[django.core.validators.MinValueValidator(0)])),
                ('violent_rate_murder', models.FloatField(help_text='Murder rate per 100,000 population', validators=[django.core.validators.MinValueValidator(0)])),
                ('violent_rate_rape', models.FloatField(help_text='Rape rate per 100,000 population', validators=[django.core.validators.MinValueValidator(0)])),
                ('violent_rate_robbery', models.FloatField(help_text='Robbery rate per 100,000 population', validators=[django.core.validators.MinValueValidator(0)])),
                ('property_total_all', models.IntegerField(help_text='Total property crimes', validators=[django.core.validators.MinValueValidator(0)])),
                ('property_total_burglary', models.IntegerField(help_text='Total burglaries', validators=[django.core.validators.MinValueValidator(0)])),
                ('property_total_larceny', models.IntegerField(help_text='Total larceny cases', validators=[django.core.validators.MinValueValidator(0)])),
                ('property_total_motor', models.IntegerField(help_text='Total motor vehicle thefts', validators=[django.core.validators.MinValueValidator(0)])),
                ('violent_total_all', models.IntegerField(help_text='Total violent crimes', validators=[django.core.validators.MinValueValidator(0)])),
                ('violent_total_assault', models.IntegerField(help_text='Total assaults', validators=[django.core.validators.MinValueValidator(0)])),
                ('violent_total_murder', models.IntegerField(help_text='Total murders', validators=[django.core.validators.MinValueValidator(0)])),
                ('violent_total_rape', models.IntegerField(help_text='Total rapes', validators=[django.core.validators.MinValueValidator(0)])),
                ('violent_total_robbery', models.IntegerField(help_text='Total robberies', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Crime Data',
                'verbose_name_plural': 'Crime Data',
                'ordering': ['-year', 'state'],
                'indexes': [models.Index(fields=['state', 'year'], name='crime_api_c_state_d97fce_idx'), models.Index(fields=['year'], name='crime_api_c_year_40acd2_idx'), models.Index(fields=['state'], name='crime_api_c_state_0dd4b5_idx')],
                'unique_together': {('state', 'year')},
            },
        ),
    ]
